Feature bubble sort project
alejandrotoledoweb/bubble-sort pull request #1
Opened 2020-10-14 20:02 UTC by alejandrotoledoweb

## Feature Bubble Sort Project

This project was build with RUBY.

This project contains two methods:
- First Method: sorts the number inside an array
- Second Method: sorts words inside and array

2020-10-14 20:51 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, you're required to do these changes, listed below:
  
## [REQUIRED CHANGES]
- [ ] Your linters is throwing errors, please fix it;
- [ ] Your `bubble_sort_by` method is also throwing errors when users try to pass an empty bock through it. Tip:  you can fix it by using yield
![image](https://user-images.githubusercontent.com/56762529/96043395-45b5b280-0e45-11eb-9878-a5a2c4462992.png)
- [ ] Improve your readme descriptiveness, like at the setup section. Describe what the user should do to see what you did in this project. Assume that the user doesn't have any knowledge in ruby or programming languages, it will help you when you be required to write some documentation, for example.

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-10-14 22:53 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

Hello @julian3493 and @alejandrotoledoweb, Great job! 👏  so far.
Let's make a few changes, and we will be done.

- [ ] You are yet to fix the error requested by the previous TSE.  You can use `block_given?` to check if block is given or not.
<img width="634" alt="Screen Shot 2020-10-14 at 11 38 12 PM" src="https://user-images.githubusercontent.com/5264771/96052967-7feb7800-0e76-11eb-9ee9-887ce7d3692e.png">

- [ ] Kindly check the comment below as well.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-14 22:53 UTC, acushlakoncept commented on bubble_sort.rb
> +  yield p arr
An error occurred while loading ./bubble_sort_spec.rb.
`Failure/Error: yield p arr`

Kindly check this line of code to fix the issue.

2020-10-15 15:37 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for making the suggested changes
However there is still some bugs

1. Look at this, please
```rb
Traceback (most recent call last):
        7: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
        6: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
        5: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `<main>'
        4: from /home/maelfosso/.rvm/gems/ruby-2.6.5/bin/irb:23:in `load'
        3: from /home/maelfosso/.rvm/gems/ruby-2.6.5/gems/irb-1.2.4/exe/irb:11:in `<top (required)>'
        2: from (irb):1
        1: from (irb):1:in `load'
SyntaxError (bubble_sort.rb:28: syntax error, unexpected '=')
        var = arr[i] < = > arr[i - 1]
                       ^
2.6.5 :002 > 
```
Kindly fix it by using `<=>`, remove space

2- Also, raises an error if block is not given to the `bubble_sort_by` method.

Kindly make the suggested changes and once done submit a new code review request
Thanks

Mael FOSSO

2020-10-15 16:31 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Hello team! 
Good job with the implemented changes! 👏 
But we still have a problem with the bubble_sort_by method when no block is given, in that situation the method should raise an error.
Kindly fix the issue and resubmit your project for a new code review.

Good luck 😺

2020-10-15 17:28 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__Although we still have some changes to make, you have done an excellent job on this project. Kindly check my comments below and fix the issues as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] Your algorithms (methods) should `return` and `not print` the sorted array. Kindly remove the `p` and just return the sorted array.

![18-17-29](https://user-images.githubusercontent.com/26856491/96164134-b545a380-0f12-11eb-945e-ac1b2abc4c0f.png)

- [ ] Your `bubble_sort_by` does not pass all the test cases.
- As mentioned by the previous reviewers, your **`bubble_sort_by raises an error if block is not given`.** This means that when your `bubble_sort_by` is tested with no block, it is expected to return an error `LocalJumpError`, but it does not.

If I test your `bubble_sort_by` with the code snippet below:

`bubble_sort_by(%w[hello hi hey])`

This should return an error because the `bubble_sort_by` should only work when a block is given. 

But in your case, it does not return an error. The fact that it doesn't return an error is something you should look into.

**[ COMMENTS ]**
- I can see that you have some inline comments on your project. To me, I think these comments are unnecessary. This is because the code itself is self-explanatory. If you think the same way too, you can remove those comments.

**Please make the required changes and submit another review request when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**
__Happy Coding :smiley:__

2020-10-15 18:42 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations team :tada:  this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

Do not forget to fill the **project completion form.**
Also, remember to **merge this branch to master.**
_Good luck with your next task._

**I'm @taofeekolalere on slack.
Happy Coding :man_technologist:**

2020-10-15 19:15 UTC, merged